version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../:/trading_workspace
    ports:
      - "8888:8888"
